/* Track — private food/symptom log
 * Pure browser app: Supabase URL+publishable key are AES-GCM encrypted in this file
 * with a key derived from the password (PBKDF2). No backend.
 */
(function () {
  'use strict';

  // ============ ENCRYPTED CONFIG ============
  // Generated by .claude/encrypt-config.mjs. Plaintext is "<url>|<publishable_key>".
  // Without the password, this blob can't be decrypted.
  const ENCRYPTED_CONFIG = {
    salt: 'KHBWLiqX3qp81dxsw9D2cQ==',
    iv: 'ALBp40hLVxD3GE3d',
    ciphertext: 'tdYzx2XODLDSD06tAFyfsoxZnBhP0EWdsdopr+3UM3A8h3O8HpjGyQkN72or4iQ6Fr5K8MF/lSI3UFZ1UR2w0+jS1YBINCWepIR/FXYHP01jKg4x1cDhVVINXN1d0vlAOtjU/AKhpw==',
    iterations: 600000,
  };

  const STORAGE_KEY = 'track-config-v1';
  const FETCH_DAYS = 30;
  const TRIGGER_WINDOW_MIN_H = 4;
  const TRIGGER_WINDOW_MAX_H = 24;
  const STOPWORDS = new Set(['a','an','the','of','with','and','or','for','to','in','on','at','as','my','is','i','was','it','some','from','one','two','three','few','about','that','this','had','have']);

  // ============ STATE ============
  let sb = null;
  let foods = [];
  let symptoms = [];
  let activeTab = 'timeline';
  let activeTrigger = 'burp';
  let editing = null; // { kind: 'food'|'symptom', data }

  // ============ DOM HELPERS ============
  const $ = (s, root) => (root || document).querySelector(s);
  const $$ = (s, root) => Array.from((root || document).querySelectorAll(s));
  const escapeHtml = (str) => String(str ?? '').replace(/[&<>"']/g, (c) => ({
    '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;'
  }[c]));

  const b64decode = (s) => {
    const bin = atob(s);
    const out = new Uint8Array(bin.length);
    for (let i = 0; i < bin.length; i++) out[i] = bin.charCodeAt(i);
    return out;
  };

  // ============ TIME HELPERS ============
  const pad2 = (n) => String(n).padStart(2, '0');
  const formatTime = (d) => `${pad2(d.getHours())}:${pad2(d.getMinutes())}`;
  const datetimeLocalString = (d) =>
    `${d.getFullYear()}-${pad2(d.getMonth() + 1)}-${pad2(d.getDate())}T${pad2(d.getHours())}:${pad2(d.getMinutes())}`;
  const dayKey = (d) => `${d.getFullYear()}-${d.getMonth()}-${d.getDate()}`;

  function dayLabel(d) {
    const today = new Date(); today.setHours(0, 0, 0, 0);
    const yesterday = new Date(today); yesterday.setDate(yesterday.getDate() - 1);
    const target = new Date(d); target.setHours(0, 0, 0, 0);
    if (target.getTime() === today.getTime()) return 'TODAY';
    if (target.getTime() === yesterday.getTime()) return 'YESTERDAY';
    return d.toLocaleDateString('en-US', { weekday: 'short', month: 'short', day: 'numeric' }).toUpperCase();
  }

  // ============ DECRYPT CONFIG ============
  async function decryptConfig(password) {
    const enc = new TextEncoder();
    const baseKey = await crypto.subtle.importKey('raw', enc.encode(password), 'PBKDF2', false, ['deriveKey']);
    const key = await crypto.subtle.deriveKey(
      {
        name: 'PBKDF2',
        salt: b64decode(ENCRYPTED_CONFIG.salt),
        iterations: ENCRYPTED_CONFIG.iterations,
        hash: 'SHA-256'
      },
      baseKey,
      { name: 'AES-GCM', length: 256 },
      false,
      ['decrypt']
    );
    const plaintextBuf = await crypto.subtle.decrypt(
      { name: 'AES-GCM', iv: b64decode(ENCRYPTED_CONFIG.iv) },
      key,
      b64decode(ENCRYPTED_CONFIG.ciphertext)
    );
    const plaintext = new TextDecoder().decode(plaintextBuf);
    const [url, anonKey] = plaintext.split('|');
    if (!url || !anonKey) throw new Error('bad blob');
    return { url, anonKey };
  }

  // ============ LOGIN ============
  function bindLogin() {
    const form = $('#login-form');
    const btn = $('#unlock-btn');
    const err = $('#login-error');
    form.addEventListener('submit', async (e) => {
      e.preventDefault();
      err.textContent = '';
      btn.disabled = true;
      btn.textContent = 'Unlocking…';
      const pw = $('#pw').value;
      try {
        const config = await decryptConfig(pw);
        sessionStorage.setItem(STORAGE_KEY, JSON.stringify(config));
        await startApp(config);
      } catch (ex) {
        err.textContent = 'Wrong password.';
        btn.disabled = false;
        btn.textContent = 'Unlock';
        $('#pw').select();
      }
    });
  }

  function lock() {
    sessionStorage.removeItem(STORAGE_KEY);
    location.reload();
  }

  // ============ APP INIT ============
  async function startApp(config) {
    sb = window.supabase.createClient(config.url, config.anonKey, {
      auth: { persistSession: false, autoRefreshToken: false, detectSessionInUrl: false }
    });
    $('#login').hidden = true;
    $('#app').hidden = false;
    bindAppEvents();
    bindShortcuts();
    await refresh();
  }

  function bindAppEvents() {
    $('#lock-btn').addEventListener('click', lock);
    $('#btn-food').addEventListener('click', () => openModal('food'));
    $('#btn-symptom').addEventListener('click', () => openModal('symptom'));
    $$('#tabs .tab').forEach((tab) => {
      tab.addEventListener('click', () => switchTab(tab.dataset.tab));
    });
    const dialog = $('#entry-modal');
    $('#modal-close').addEventListener('click', () => dialog.close());
    dialog.addEventListener('click', (e) => {
      if (e.target === dialog) dialog.close();
    });
  }

  function bindShortcuts() {
    document.addEventListener('keydown', (e) => {
      if (e.metaKey || e.ctrlKey || e.altKey) return;
      const tag = (e.target.tagName || '').toLowerCase();
      if (tag === 'input' || tag === 'textarea' || tag === 'select') return;
      if ($('#entry-modal').open) return;
      if (e.key === 'f' || e.key === 'F') { e.preventDefault(); openModal('food'); }
      else if (e.key === 's' || e.key === 'S') { e.preventDefault(); openModal('symptom'); }
      else if (e.key === '1') switchTab('timeline');
      else if (e.key === '2') switchTab('suspects');
      else if (e.key === 'r' || e.key === 'R') refresh();
    });
  }

  function switchTab(name) {
    activeTab = name;
    $$('#tabs .tab').forEach(t => t.classList.toggle('active', t.dataset.tab === name));
    $('#tab-timeline').hidden = name !== 'timeline';
    $('#tab-suspects').hidden = name !== 'suspects';
    render();
  }

  // ============ DATA ============
  async function fetchData() {
    setNet('busy');
    try {
      const sinceIso = new Date(Date.now() - FETCH_DAYS * 24 * 3600 * 1000).toISOString();
      const [foodRes, sympRes] = await Promise.all([
        sb.from('food_entries').select('*').gte('consumed_at', sinceIso).order('consumed_at', { ascending: false }),
        sb.from('symptom_entries').select('*').gte('occurred_at', sinceIso).order('occurred_at', { ascending: false }),
      ]);
      if (foodRes.error) throw foodRes.error;
      if (sympRes.error) throw sympRes.error;
      foods = foodRes.data || [];
      symptoms = sympRes.data || [];
      setNet('ok');
    } catch (e) {
      console.error(e);
      setNet('offline');
      toast('Could not fetch — ' + (e.message || e), true);
    }
  }

  async function refresh() {
    await fetchData();
    render();
  }

  // ============ RENDER ============
  function render() {
    $('#count-timeline').textContent = `(${foods.length + symptoms.length})`;
    if (activeTab === 'timeline') renderTimeline();
    else renderSuspects();
  }

  function renderTimeline() {
    const container = $('#tab-timeline');
    const items = [
      ...foods.map(f => ({ kind: 'food', t: new Date(f.consumed_at), data: f })),
      ...symptoms.map(s => ({ kind: 'symptom', t: new Date(s.occurred_at), data: s })),
    ].sort((a, b) => b.t - a.t);

    if (!items.length) {
      container.innerHTML = `<div class="empty">
        <strong>Nothing logged yet.</strong>
        Tap <em>Food / Drink</em> or <em>Symptom</em> above to start.
      </div>`;
      return;
    }

    const days = new Map();
    for (const it of items) {
      const k = dayKey(it.t);
      if (!days.has(k)) days.set(k, []);
      days.get(k).push(it);
    }

    let html = '';
    for (const [k, dayItems] of days) {
      const headerLabel = dayLabel(dayItems[0].t);
      const foodCount = dayItems.filter(i => i.kind === 'food').length;
      const sympCount = dayItems.filter(i => i.kind === 'symptom').length;
      html += `<div class="day">
        <div class="day-head">
          <span>${headerLabel}</span>
          <span class="day-meta">${foodCount} food · ${sympCount} symptom</span>
        </div>`;
      for (const it of dayItems) {
        html += renderEntry(it);
      }
      html += `</div>`;
    }
    container.innerHTML = html;

    container.querySelectorAll('[data-entry]').forEach(el => {
      el.addEventListener('click', () => {
        const [kind, id] = el.dataset.entry.split(':');
        const entry = (kind === 'food' ? foods : symptoms).find(e => e.id === id);
        if (entry) openModal(kind, entry);
      });
    });
  }

  function renderEntry(it) {
    const time = formatTime(it.t);
    if (it.kind === 'food') {
      const f = it.data;
      const tags = (f.tags || []).map(t => `<span class="tag">${escapeHtml(t)}</span>`).join('');
      const meta = (tags || !f.tags?.length)
        ? `<div class="entry-meta">${tags || '<span class="tag add">+ tag</span>'}</div>`
        : '';
      const notes = f.notes ? `<div class="entry-notes">${escapeHtml(f.notes)}</div>` : '';
      return `<div class="entry food" data-entry="food:${f.id}">
        <div class="entry-time">${time}</div>
        <div class="entry-mark"></div>
        <div class="entry-body">
          <div class="entry-title">${escapeHtml(f.description)}</div>
          ${meta}
          ${notes}
        </div>
      </div>`;
    } else {
      const s = it.data;
      const typeName = s.type === 'other' ? (s.type_other || 'other') : s.type;
      const sevHtml = s.severity ? `<div class="entry-meta"><span class="severity">${renderSeverity(s.severity)}</span></div>` : '';
      const notes = s.notes ? `<div class="entry-notes">${escapeHtml(s.notes)}</div>` : '';
      return `<div class="entry symptom symptom-${s.type}" data-entry="symptom:${s.id}">
        <div class="entry-time">${time}</div>
        <div class="entry-mark symptom-${s.type}"></div>
        <div class="entry-body">
          <div class="entry-title">${escapeHtml(typeName)}</div>
          ${sevHtml}
          ${notes}
        </div>
      </div>`;
    }
  }

  function renderSeverity(sev) {
    let html = '';
    for (let i = 1; i <= 5; i++) {
      html += i <= sev ? '<span class="filled">●</span>' : '<span>○</span>';
    }
    return html;
  }

  // ============ SUSPECTS ============
  function extractTokens(food) {
    const tokens = new Set();
    for (const t of (food.tags || [])) {
      const v = String(t).toLowerCase().trim();
      if (v) tokens.add(v);
    }
    const words = String(food.description || '').toLowerCase().split(/[\s,/+&()\-]+/);
    for (const w of words) {
      const t = w.trim();
      if (t.length < 3) continue;
      if (STOPWORDS.has(t)) continue;
      tokens.add(t);
    }
    return tokens;
  }

  function renderSuspects() {
    const container = $('#tab-suspects');
    const triggers = symptoms.filter(s => activeTrigger === 'any' ? true : s.type === activeTrigger);

    const triggerLabel = activeTrigger === 'any' ? 'symptom' : activeTrigger;
    let html = `<div class="suspects-head">
      Foods/tags eaten <strong>${TRIGGER_WINDOW_MIN_H}–${TRIGGER_WINDOW_MAX_H}h</strong> before each
      <select id="trigger-select">
        <option value="burp"${activeTrigger === 'burp' ? ' selected' : ''}>burp</option>
        <option value="diarrhea"${activeTrigger === 'diarrhea' ? ' selected' : ''}>diarrhea</option>
        <option value="other"${activeTrigger === 'other' ? ' selected' : ''}>other</option>
        <option value="any"${activeTrigger === 'any' ? ' selected' : ''}>any symptom</option>
      </select>
      event, last ${FETCH_DAYS} days · <strong>${triggers.length}</strong> episode${triggers.length === 1 ? '' : 's'}.
    </div>`;

    if (!triggers.length) {
      html += `<div class="empty"><strong>No ${triggerLabel} events in window.</strong>Once you've logged some, suspects appear here.</div>`;
      container.innerHTML = html;
      $('#trigger-select')?.addEventListener('change', (e) => {
        activeTrigger = e.target.value;
        renderSuspects();
      });
      return;
    }

    const stats = new Map(); // token -> { episodes: Set<symptomId>, examples: Set<string> }
    for (const symp of triggers) {
      const tEnd = new Date(symp.occurred_at).getTime() - TRIGGER_WINDOW_MIN_H * 3600 * 1000;
      const tStart = new Date(symp.occurred_at).getTime() - TRIGGER_WINDOW_MAX_H * 3600 * 1000;
      const candidates = foods.filter(f => {
        const t = new Date(f.consumed_at).getTime();
        return t >= tStart && t <= tEnd;
      });
      const episodeTokens = new Map(); // token -> example description
      for (const f of candidates) {
        for (const tok of extractTokens(f)) {
          if (!episodeTokens.has(tok)) episodeTokens.set(tok, f.description);
        }
      }
      for (const [tok, example] of episodeTokens) {
        if (!stats.has(tok)) stats.set(tok, { episodes: new Set(), examples: new Set() });
        const st = stats.get(tok);
        st.episodes.add(symp.id);
        st.examples.add(example);
      }
    }

    const ranked = [...stats.entries()]
      .map(([tok, st]) => ({ token: tok, count: st.episodes.size, examples: [...st.examples] }))
      .filter(r => triggers.length < 2 ? r.count >= 1 : r.count >= 2)
      .sort((a, b) => b.count - a.count || a.token.localeCompare(b.token));

    if (!ranked.length) {
      html += `<div class="empty">No food logged in the ${TRIGGER_WINDOW_MIN_H}–${TRIGGER_WINDOW_MAX_H}h windows yet.</div>`;
    } else {
      for (let i = 0; i < ranked.length; i++) {
        const r = ranked[i];
        const rank = i + 1;
        const rankClass = rank === 1 ? 'top1' : rank === 2 ? 'top2' : rank === 3 ? 'top3' : '';
        const examples = r.examples.slice(0, 3).join(', ');
        html += `<div class="suspect">
          <div class="suspect-rank ${rankClass}">#${rank}</div>
          <div>
            <div class="suspect-name">${escapeHtml(r.token)}</div>
            <div class="suspect-detail">e.g. ${escapeHtml(examples)}</div>
          </div>
          <div class="suspect-count">${r.count}<span style="color:var(--ink-faded);font-weight:400">/${triggers.length}</span></div>
        </div>`;
      }
    }

    container.innerHTML = html;
    $('#trigger-select')?.addEventListener('change', (e) => {
      activeTrigger = e.target.value;
      renderSuspects();
    });
  }

  // ============ MODAL ============
  function openModal(kind, entry) {
    editing = entry ? { kind, data: entry } : null;
    const dialog = $('#entry-modal');
    $('#modal-title').textContent = entry
      ? `Edit ${kind}`
      : (kind === 'food' ? 'Log food / drink' : 'Log symptom');
    $('#entry-form').innerHTML = kind === 'food'
      ? foodFormHtml(entry)
      : symptomFormHtml(entry);
    bindFormEvents(kind);
    dialog.showModal();
    const first = $('#entry-form input, #entry-form textarea, #entry-form button.type-btn');
    if (first && !entry) setTimeout(() => first.focus?.(), 50);
  }

  function foodFormHtml(entry) {
    const now = new Date();
    const when = entry ? new Date(entry.consumed_at) : now;
    const desc = entry ? entry.description : '';
    const tags = entry ? (entry.tags || []).join(', ') : '';
    const notes = entry ? (entry.notes || '') : '';
    return `
      <div class="field">
        <label class="field-label">What</label>
        <input type="text" name="description" required placeholder="e.g. coffee, lasagna, beer" value="${escapeHtml(desc)}">
      </div>
      <div class="field">
        <label class="field-label">When</label>
        <input type="datetime-local" name="when" required value="${datetimeLocalString(when)}">
        <div class="quick-time">
          <button type="button" data-when="0">now</button>
          <button type="button" data-when="-15">15m ago</button>
          <button type="button" data-when="-30">30m ago</button>
          <button type="button" data-when="-60">1h ago</button>
          <button type="button" data-when="-180">3h ago</button>
        </div>
      </div>
      <div class="field">
        <label class="field-label">Tags <span style="color:var(--ink-faded);text-transform:none;letter-spacing:0;font-size:10px">comma-separated, optional</span></label>
        <input type="text" name="tags" placeholder="dairy, spicy, ate out" value="${escapeHtml(tags)}">
      </div>
      <div class="field">
        <label class="field-label">Notes <span style="color:var(--ink-faded);text-transform:none;letter-spacing:0;font-size:10px">optional</span></label>
        <textarea name="notes" placeholder="">${escapeHtml(notes)}</textarea>
      </div>
      <div class="modal-actions">
        ${entry ? '<button type="button" class="btn btn-danger" id="delete-btn">Delete</button>' : ''}
        <button type="submit" class="btn btn-primary">${entry ? 'Save' : 'Log it'}</button>
      </div>
    `;
  }

  function symptomFormHtml(entry) {
    const now = new Date();
    const when = entry ? new Date(entry.occurred_at) : now;
    const type = entry ? entry.type : '';
    const typeOther = entry ? (entry.type_other || '') : '';
    const sev = entry ? entry.severity : '';
    const notes = entry ? (entry.notes || '') : '';
    return `
      <div class="field">
        <label class="field-label">Type</label>
        <div class="type-grid">
          <button type="button" class="type-btn${type === 'burp' ? ' selected' : ''}" data-type="burp">Burp</button>
          <button type="button" class="type-btn${type === 'diarrhea' ? ' selected' : ''}" data-type="diarrhea">Diarrhea</button>
          <button type="button" class="type-btn${type === 'other' ? ' selected' : ''}" data-type="other">Other</button>
        </div>
        <input type="hidden" name="type" value="${escapeHtml(type)}" required>
        <input type="text" name="type_other" placeholder="describe…" value="${escapeHtml(typeOther)}" style="margin-top:8px;width:100%;padding:10px 12px;background:var(--bg);border:1px solid var(--line);border-radius:6px;color:var(--ink);font-size:14px;${type === 'other' ? '' : 'display:none;'}">
      </div>
      <div class="field">
        <label class="field-label">When</label>
        <input type="datetime-local" name="when" required value="${datetimeLocalString(when)}">
        <div class="quick-time">
          <button type="button" data-when="0">now</button>
          <button type="button" data-when="-15">15m ago</button>
          <button type="button" data-when="-30">30m ago</button>
          <button type="button" data-when="-60">1h ago</button>
          <button type="button" data-when="-180">3h ago</button>
        </div>
      </div>
      <div class="field">
        <label class="field-label">Severity <span style="color:var(--ink-faded);text-transform:none;letter-spacing:0;font-size:10px">1=mild, 5=brutal · optional</span></label>
        <div class="severity-grid">
          ${[1,2,3,4,5].map(n => `<button type="button" class="sev-btn${sev === n ? ' selected' : ''}" data-sev="${n}">${n}</button>`).join('')}
        </div>
        <input type="hidden" name="severity" value="${sev || ''}">
      </div>
      <div class="field">
        <label class="field-label">Notes <span style="color:var(--ink-faded);text-transform:none;letter-spacing:0;font-size:10px">optional</span></label>
        <textarea name="notes">${escapeHtml(notes)}</textarea>
      </div>
      <div class="modal-actions">
        ${entry ? '<button type="button" class="btn btn-danger" id="delete-btn">Delete</button>' : ''}
        <button type="submit" class="btn btn-primary">${entry ? 'Save' : 'Log it'}</button>
      </div>
    `;
  }

  function bindFormEvents(kind) {
    const form = $('#entry-form');

    // quick-time buttons
    form.querySelectorAll('.quick-time button').forEach(btn => {
      btn.addEventListener('click', () => {
        const offset = parseInt(btn.dataset.when, 10);
        const t = new Date(Date.now() + offset * 60 * 1000);
        form.querySelector('[name="when"]').value = datetimeLocalString(t);
      });
    });

    if (kind === 'symptom') {
      // type buttons
      form.querySelectorAll('.type-btn').forEach(btn => {
        btn.addEventListener('click', () => {
          form.querySelectorAll('.type-btn').forEach(b => b.classList.remove('selected'));
          btn.classList.add('selected');
          form.querySelector('[name="type"]').value = btn.dataset.type;
          const otherInput = form.querySelector('[name="type_other"]');
          if (btn.dataset.type === 'other') {
            otherInput.style.display = '';
            setTimeout(() => otherInput.focus(), 50);
          } else {
            otherInput.style.display = 'none';
            otherInput.value = '';
          }
        });
      });

      // severity buttons
      form.querySelectorAll('.sev-btn').forEach(btn => {
        btn.addEventListener('click', () => {
          const sev = parseInt(btn.dataset.sev, 10);
          const current = parseInt(form.querySelector('[name="severity"]').value, 10);
          if (current === sev) {
            // toggle off
            form.querySelector('[name="severity"]').value = '';
            form.querySelectorAll('.sev-btn').forEach(b => b.classList.remove('selected'));
          } else {
            form.querySelector('[name="severity"]').value = sev;
            form.querySelectorAll('.sev-btn').forEach(b => b.classList.toggle('selected', parseInt(b.dataset.sev, 10) === sev));
          }
        });
      });
    }

    form.onsubmit = (e) => { e.preventDefault(); submitEntry(kind); };

    const delBtn = $('#delete-btn');
    if (delBtn) delBtn.addEventListener('click', () => deleteEntry(kind));
  }

  async function submitEntry(kind) {
    const form = $('#entry-form');
    const data = Object.fromEntries(new FormData(form));
    const submitBtn = form.querySelector('button[type="submit"]');
    submitBtn.disabled = true;
    submitBtn.textContent = 'Saving…';

    try {
      const whenIso = new Date(data.when).toISOString();
      let res;
      if (kind === 'food') {
        const tags = String(data.tags || '')
          .split(',').map(s => s.trim()).filter(Boolean);
        const payload = {
          consumed_at: whenIso,
          description: String(data.description).trim(),
          tags,
          notes: data.notes?.trim() || null,
        };
        if (editing) {
          res = await sb.from('food_entries').update(payload).eq('id', editing.data.id);
        } else {
          res = await sb.from('food_entries').insert(payload);
        }
      } else {
        if (!data.type) throw new Error('Pick a symptom type');
        const payload = {
          occurred_at: whenIso,
          type: data.type,
          type_other: data.type === 'other' ? (data.type_other?.trim() || null) : null,
          severity: data.severity ? parseInt(data.severity, 10) : null,
          notes: data.notes?.trim() || null,
        };
        if (editing) {
          res = await sb.from('symptom_entries').update(payload).eq('id', editing.data.id);
        } else {
          res = await sb.from('symptom_entries').insert(payload);
        }
      }
      if (res.error) throw res.error;
      $('#entry-modal').close();
      toast(editing ? 'Updated.' : 'Logged.');
      await refresh();
    } catch (e) {
      console.error(e);
      toast(e.message || String(e), true);
      submitBtn.disabled = false;
      submitBtn.textContent = editing ? 'Save' : 'Log it';
    }
  }

  async function deleteEntry(kind) {
    if (!editing) return;
    if (!confirm('Delete this entry?')) return;
    const table = kind === 'food' ? 'food_entries' : 'symptom_entries';
    try {
      const res = await sb.from(table).delete().eq('id', editing.data.id);
      if (res.error) throw res.error;
      $('#entry-modal').close();
      toast('Deleted.');
      await refresh();
    } catch (e) {
      console.error(e);
      toast(e.message || String(e), true);
    }
  }

  // ============ TOAST + NET ============
  let toastTimer = null;
  function toast(msg, isError) {
    const el = $('#toast');
    el.textContent = msg;
    el.classList.toggle('error', !!isError);
    el.classList.add('show');
    clearTimeout(toastTimer);
    toastTimer = setTimeout(() => el.classList.remove('show'), 3000);
  }

  function setNet(state) {
    const dot = $('#net-dot');
    dot.classList.remove('offline', 'busy');
    if (state === 'offline') { dot.classList.add('offline'); dot.title = 'Offline'; }
    else if (state === 'busy') { dot.classList.add('busy'); dot.title = 'Loading'; }
    else dot.title = 'Connected';
  }

  // ============ BOOT ============
  function init() {
    bindLogin();
    const stored = sessionStorage.getItem(STORAGE_KEY);
    if (stored) {
      try {
        const config = JSON.parse(stored);
        if (config.url && config.anonKey) startApp(config);
      } catch {}
    }
  }

  init();
})();
